// Generated by ReScript, PLEASE EDIT WITH CARE


var countText = document.getElementById("count");

var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var counter = {
  contents: 0
};

function plusOperation(count) {
  counter.contents = counter.contents + count | 0;
  return counter.contents;
}

function minusOperation(count) {
  counter.contents = counter.contents - count | 0;
  return counter.contents;
}

function handleClass(count) {
  if (count > 0) {
    return "count-positive";
  } else if (count < 0) {
    return "count-negative";
  } else {
    return "count-zero";
  }
}

function renderCount(count) {
  countText.textContent = count;
  countText.className = handleClass(count) + " count";
  
}

plusButton.addEventListener("click", (function (param) {
        return renderCount(plusOperation(1));
      }));

minusButton.addEventListener("click", (function (param) {
        return renderCount(minusOperation(1));
      }));

export {
  countText ,
  plusButton ,
  minusButton ,
  counter ,
  plusOperation ,
  minusOperation ,
  handleClass ,
  renderCount ,
  
}
/* countText Not a pure module */
